services:
  - type: web
    name: electrohive
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: MONGO_URI
        fromService:
          name: electrohive-mongodb
          type: mongodb
          property: connectionString.standardSrv

databases:
  - name: electrohive-mongodb
    databaseName: rsportronics
    plan: free
    teamId: your-team-id  # Remove this line if not using teams
